Firmware SDK: bc_adc
bc_adc
Driver for ADC (analog to digital converter)
Enumerations
enum bc_adc_channel_t {
BC_ADC_CHANNEL_A0 = 0,
BC_ADC_CHANNEL_A1 = 1,
BC_ADC_CHANNEL_A2 = 2,
BC_ADC_CHANNEL_A3 = 3,
BC_ADC_CHANNEL_A4 = 4,
BC_ADC_CHANNEL_A5 = 5
}
ADC channel.
enum bc_adc_format_t {
BC_ADC_FORMAT_8_BIT = 0,
BC_ADC_FORMAT_16_BIT = 1,
BC_ADC_FORMAT_24_BIT = 2,
BC_ADC_FORMAT_32_BIT = 3,
BC_ADC_FORMAT_FLOAT = 4
}
ADC result format.
enum bc_adc_event_t { BC_ADC_EVENT_DONE }
ADC event.
Functions
void bc_adc_init (bc_adc_channel_t channel, bc_adc_format_t format)
Initialize ADC channel.
void bc_adc_set_format (bc_adc_channel_t channel, bc_adc_format_t format)
Set ADC result format.
bc_adc_format_t bc_adc_get_format (bc_adc_channel_t channel)
Get ADC result format.
bool bc_adc_is_ready (bc_adc_channel_t channel)
Check if ADC is ready for reading.
bool bc_adc_read (bc_adc_channel_t channel, void *result)
Reads the ADC channel voltage.
bool bc_adc_set_event_handler (bc_adc_channel_t channel, void(*event_handler)(bc_adc_channel_t, bc_adc_event_t, void *), void *event_param)
Set callback function.
bool bc_adc_async_read (bc_adc_channel_t channel)
Begins reading the ADC channel voltage in asynchronous mode.
bool bc_adc_get_result (bc_adc_channel_t channel, void *result)
Get measurement result.
bool bc_adc_get_vdda_voltage (float *vdda_voltage)
Get voltage on VDDA pin.
bool bc_adc_calibration (void)
Calibration.
Detailed Description
Driver for ADC (analog to digital converter)
Enumeration Type Documentation
enum bc_adc_channel_t
ADC channel.
Enumerator
BC_ADC_CHANNEL_A0
ADC channel A0.
BC_ADC_CHANNEL_A1
ADC channel A1.
BC_ADC_CHANNEL_A2
ADC channel A2.
BC_ADC_CHANNEL_A3
ADC channel A3.
BC_ADC_CHANNEL_A4
ADC channel A4.
BC_ADC_CHANNEL_A5
ADC channel A5.
Definition at line 12 of file bc_adc.h.
enum bc_adc_event_t
ADC event.
Enumerator
BC_ADC_EVENT_DONE
ADC event.
Definition at line 57 of file bc_adc.h.
enum bc_adc_format_t
ADC result format.
Enumerator
BC_ADC_FORMAT_8_BIT
ADC result format is 8-bit.
BC_ADC_FORMAT_16_BIT
ADC result format is 16-bit.
BC_ADC_FORMAT_24_BIT
ADC result format is 24-bit.
BC_ADC_FORMAT_32_BIT
ADC result format is 32-bit.
BC_ADC_FORMAT_FLOAT
ADC result format is float.
Definition at line 36 of file bc_adc.h.
Function Documentation
bool bc_adc_async_read (bc_adc_channel_t channel)
Begins reading the ADC channel voltage in asynchronous mode.
Parameters
[in] channel ADC channel
Returns
true On success
false On failure
Definition at line 162 of file bc_adc.c.
bool bc_adc_calibration (void)
Calibration.
Returns
true On success
false On failure
Definition at line 312 of file bc_adc.c.
bc_adc_format_t bc_adc_get_format (bc_adc_channel_t channel)
Get ADC result format.
Parameters
[in] channel ADC channel
Returns
ADC result format
Definition at line 100 of file bc_adc.c.
bool bc_adc_get_result (bc_adc_channel_t channel, void * result)
Get measurement result.
Parameters
[in] channel ADC channel
[out] result Pointer to variable where result will be stored
Returns
true On success
false On failure
Definition at line 196 of file bc_adc.c.
Referenced by bc_adc_read().
bool bc_adc_get_vdda_voltage (float * vdda_voltage)
Get voltage on VDDA pin.
Parameters
[out] vdda_voltage Pointer to destination where VDDA will be stored
Returns
true On valid VDDA
false On valid VDDA
Definition at line 237 of file bc_adc.c.
void bc_adc_init (bc_adc_channel_t channel, bc_adc_format_t format)
Initialize ADC channel.
Parameters
[in] channel ADC channel
[in] format ADC result format
Definition at line 60 of file bc_adc.c.
Referenced by bc_analog_sensor_init().
bool bc_adc_is_ready (bc_adc_channel_t channel)
Check if ADC is ready for reading.
Parameters
[in] self Instance
Returns
true If ready
false If not ready
Definition at line 105 of file bc_adc.c.
bool bc_adc_read (bc_adc_channel_t channel, void * result)
Reads the ADC channel voltage.
Parameters
[in] channel ADC channel
[out] result Pointer to destination where ADC conversion will be stored
Returns
true On success
false On failure
Definition at line 112 of file bc_adc.c.
bool bc_adc_set_event_handler (bc_adc_channel_t channel, void(*)(bc_adc_channel_t, bc_adc_event_t, void *) event_handler, void * event_param)
Set callback function.
Parameters
[in] channel ADC channel
[in] event_handler Function address
[in] event_param Optional event parameter (can be NULL)
Returns
true On success
false On failure
Definition at line 146 of file bc_adc.c.
Referenced by bc_analog_sensor_init().
void bc_adc_set_format (bc_adc_channel_t channel, bc_adc_format_t format)
Set ADC result format.
Parameters
[in] channel ADC channel
[in] format ADC result format
Definition at line 95 of file bc_adc.c.
Referenced by bc_adc_init().