Firmware SDK: bc_ssd1306
bc_ssd1306
Driver for SSD1306 Monochrome OLED graphic display.
Data Structures
struct bc_ssd1306_framebuffer_t
struct bc_ssd1306_t
Instance.
Macros
#define BC_SSD1306_ADDRESS_I2C_ADDRESS_DEFAULT 0x3C
#define BC_SSD1306_ADDRESS_I2C_ADDRESS_ALTERNATE 0x3D
#define BC_SSD1306_FRAMEBUFFER(NAME, WIDTH, HEIGHT)
Functions
bool bc_ssd1306_init (bc_ssd1306_t *self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address, const bc_ssd1306_framebuffer_t *framebuffer)
Initialize lcd driver.
bc_gfx_caps_t bc_ssd1306_get_caps (bc_ssd1306_t *self)
Get capabilities.
bool bc_ssd1306_is_ready (bc_ssd1306_t *self)
Check if lcd is ready for commands.
void bc_ssd1306_clear (bc_ssd1306_t *self)
Clear.
void bc_ssd1306_draw_pixel (bc_ssd1306_t *self, int x, int y, uint32_t color)
Lcd draw pixel.
uint32_t bc_ssd1306_get_pixel (bc_ssd1306_t *self, int x, int y)
Lcd get pixel.
bool bc_ssd1306_update (bc_ssd1306_t *self)
Lcd update, send data.
const bc_gfx_driver_t * bc_ssd1306_get_driver (void)
Get Lcd driver.
Detailed Description
Driver for SSD1306 Monochrome OLED graphic display.
Macro Definition Documentation
#define BC_SSD1306_FRAMEBUFFER (NAME, WIDTH, HEIGHT)
Value:
uint8_t NAME##_buffer[WIDTH * HEIGHT / 8]; \
    bc_ssd1306_framebuffer_t NAME = { \
            .buffer = NAME##_buffer, \
            .width = WIDTH, \
            .height = HEIGHT, \
            .length = sizeof(NAME##_buffer), \
            .pages = HEIGHT / 8 \
    };
Definition at line 15 of file bc_ssd1306.h.
Function Documentation
void bc_ssd1306_clear (bc_ssd1306_t * self)
Clear.
Parameters
[in] self Instance
Definition at line 68 of file bc_ssd1306.c.
Referenced by bc_ssd1306_get_driver().
void bc_ssd1306_draw_pixel (bc_ssd1306_t * self, int x, int y, uint32_t color)
Lcd draw pixel.
Parameters
[in] self Instance
[in] left Pixels from left edge
[in] top Pixels from top edge
[in] color Pixels state
Definition at line 73 of file bc_ssd1306.c.
Referenced by bc_ssd1306_get_driver().
bc_gfx_caps_t bc_ssd1306_get_caps (bc_ssd1306_t * self)
Get capabilities.
Parameters
[in] self Instance
Definition at line 51 of file bc_ssd1306.c.
Referenced by bc_ssd1306_get_driver().
uint32_t bc_ssd1306_get_pixel (bc_ssd1306_t * self, int x, int y)
Lcd get pixel.
Parameters
[in] self Instance
[in] left Pixels from left edge
[in] top Pixels from top edge
[in] color Pixels state
Definition at line 94 of file bc_ssd1306.c.
Referenced by bc_ssd1306_get_driver().
bool bc_ssd1306_init (bc_ssd1306_t * self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address, const bc_ssd1306_framebuffer_t * framebuffer)
Initialize lcd driver.
Parameters
[in] self Instance
[in] i2c_channel I2C channel
[in] i2c_address I2C device address
[in] framebuffer
Definition at line 34 of file bc_ssd1306.c.
bool bc_ssd1306_is_ready (bc_ssd1306_t * self)
Check if lcd is ready for commands.
Parameters
[in] self Instance
Returns
true If ready
false If not ready
Definition at line 58 of file bc_ssd1306.c.
Referenced by bc_ssd1306_get_driver().
bool bc_ssd1306_update (bc_ssd1306_t * self)
Lcd update, send data.
Parameters
[in] self Instance
Returns
true On success
false On failure
Definition at line 103 of file bc_ssd1306.c.
Referenced by bc_ssd1306_get_driver().