Firmware SDK: bc_ds28e17
bc_ds28e17
Driver for DS28E17 (1-wire-to-I2C Master Bridge)
Data Structures
struct bc_ds28e17_t
DS28E17 instance.
Functions
void bc_ds28e17_init (bc_ds28e17_t *self, bc_gpio_channel_t channel, uint64_t device_number)
Initialize DS28E17.
void bc_ds28e17_deinit (bc_ds28e17_t *self)
Deinitialize DS28E17.
uint64_t bc_ds28e17_get_device_number (bc_ds28e17_t *self)
Get Device number.
bool bc_ds28e17_enable_sleep_mode (bc_ds28e17_t *self)
Enable Sleep Mode.
bool bc_ds28e17_set_speed (bc_ds28e17_t *self, bc_i2c_speed_t speed)
Set I2C speed.
bool bc_ds28e17_write (bc_ds28e17_t *self, const bc_i2c_transfer_t *transfer)
Write to I2C.
bool bc_ds28e17_read (bc_ds28e17_t *self, const bc_i2c_transfer_t *transfer)
Read from I2C.
bool bc_ds28e17_memory_write (bc_ds28e17_t *self, const bc_i2c_memory_transfer_t *transfer)
Memory write to I2C.
bool bc_ds28e17_memory_read (bc_ds28e17_t *self, const bc_i2c_memory_transfer_t *transfer)
Memory read from I2C.
Detailed Description
Driver for DS28E17 (1-wire-to-I2C Master Bridge)
Function Documentation
void bc_ds28e17_deinit (bc_ds28e17_t * self)
Deinitialize DS28E17.
Parameters
[in] self Instance
Definition at line 21 of file bc_ds28e17.c.
Referenced by bc_i2c_deinit().
bool bc_ds28e17_enable_sleep_mode (bc_ds28e17_t * self)
Enable Sleep Mode.
Parameters
[in] self Instance
Definition at line 31 of file bc_ds28e17.c.
Referenced by bc_ds28e17_deinit(), and bc_ds28e17_set_speed().
uint64_t bc_ds28e17_get_device_number (bc_ds28e17_t * self)
Get Device number.
Parameters
[in] self Instance
Definition at line 26 of file bc_ds28e17.c.
void bc_ds28e17_init (bc_ds28e17_t * self, bc_gpio_channel_t channel, uint64_t device_number)
Initialize DS28E17.
Parameters
[in] self Instance
[in] channel GPIO channel
[in] device_number Device number
Definition at line 14 of file bc_ds28e17.c.
Referenced by bc_i2c_init().
bool bc_ds28e17_memory_read (bc_ds28e17_t * self, const bc_i2c_memory_transfer_t * transfer)
Memory read from I2C.
Parameters
[in] self Instance
[in] transfer Pointer to I2C memory transfer parameters instance
Returns
true On success
false On failure
Definition at line 113 of file bc_ds28e17.c.
Referenced by bc_i2c_memory_read().
bool bc_ds28e17_memory_write (bc_ds28e17_t * self, const bc_i2c_memory_transfer_t * transfer)
Memory write to I2C.
Parameters
[in] self Instance
[in] transfer Pointer to I2C memory transfer parameters instance
Returns
true On success
false On failure
Definition at line 88 of file bc_ds28e17.c.
Referenced by bc_i2c_memory_write().
bool bc_ds28e17_read (bc_ds28e17_t * self, const bc_i2c_transfer_t * transfer)
Read from I2C.
Parameters
[in] self Instance
[in] transfer Pointer to I2C transfer parameters instance
Returns
true On success
false On failure
Definition at line 77 of file bc_ds28e17.c.
Referenced by bc_i2c_read().
bool bc_ds28e17_set_speed (bc_ds28e17_t * self, bc_i2c_speed_t speed)
Set I2C speed.
Parameters
[in] self Instance
[in] speed I2C communication speed
Definition at line 45 of file bc_ds28e17.c.
Referenced by bc_i2c_set_speed().
bool bc_ds28e17_write (bc_ds28e17_t * self, const bc_i2c_transfer_t * transfer)
Write to I2C.
Parameters
[in] self Instance
[in] transfer Pointer to I2C transfer parameters instance
Returns
true On success
false On failure
Definition at line 66 of file bc_ds28e17.c.
Referenced by bc_i2c_write().